/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation DeactivateAccount($userId: ID!, $account_id: Int!) {\n  deactivate_account(userId: $userId, account_id: $account_id)\n}\n\nmutation AddAccount($userId: ID!, $input: AddAccountInput!) {\n  add_account(userId: $userId, input: $input) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}": typeof types.DeactivateAccountDocument,
    "mutation UpdateBudgetBucket($userId: ID!, $bucketId: String!, $input: UpdateBudgetBucketInput!) {\n  update_budget_bucket(userId: $userId, bucket_id: $bucketId, input: $input) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}": typeof types.UpdateBudgetBucketDocument,
    "mutation CreateMonthlyPeriod($userId: ID!, $input: CreateMonthlyPeriodInput!) {\n  create_monthly_period(userId: $userId, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nmutation UpdateMonthlyPeriod($userId: ID!, $id: Int!, $input: UpdateMonthlyPeriodInput!) {\n  update_monthly_period(userId: $userId, id: $id, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation CloseMonthlyPeriod($userId: ID!, $id: Int!) {\n  close_monthly_period(userId: $userId, id: $id) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation DeleteMonthlyPeriod($userId: ID!, $id: Int!) {\n  delete_monthly_period(userId: $userId, id: $id)\n}": typeof types.CreateMonthlyPeriodDocument,
    "mutation SplitwiseCompleteOAuth($userId: ID!, $code: String!, $state: String!) {\n  splitwise_complete_oauth(userId: $userId, code: $code, state: $state) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nmutation SplitwiseDisconnect($userId: ID!) {\n  splitwise_disconnect(userId: $userId)\n}\n\nmutation SplitwiseUpdateSettings($userId: ID!, $input: UpdateSplitwiseSettingsInput!) {\n  splitwise_update_settings(userId: $userId, input: $input) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}": typeof types.SplitwiseCompleteOAuthDocument,
    "mutation AddSyncSource($userId: ID!, $input: AddSyncSourceInput!) {\n  add_sync_source(userId: $userId, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation UpdateSyncSource($userId: ID!, $id: Int!, $input: UpdateSyncSourceInput!) {\n  update_sync_source(userId: $userId, id: $id, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation DeleteSyncSource($userId: ID!, $id: Int!) {\n  delete_sync_source(userId: $userId, id: $id)\n}\n\nmutation TestSyncSourceConnection($userId: ID!, $id: Int!) {\n  test_sync_source_connection(userId: $userId, id: $id) {\n    success\n    error_message\n  }\n}\n\nmutation SyncSyncSource($userId: ID!, $id: Int!) {\n  sync_sync_source(userId: $userId, id: $id) {\n    timestamp\n    emails_fetched\n    jobs_enqueued\n    errors\n    duration\n  }\n}": typeof types.AddSyncSourceDocument,
    "query Accounts($userId: ID!) {\n  accounts(userId: $userId) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}": typeof types.AccountsDocument,
    "query GetBudgetBuckets($userId: ID!) {\n  budget_buckets(userId: $userId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}\n\nquery GetBudgetBucket($userId: ID!, $bucketId: String!) {\n  budget_bucket(userId: $userId, bucket_id: $bucketId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}": typeof types.GetBudgetBucketsDocument,
    "query GetMonthlyPeriods($userId: ID!) {\n  monthly_periods(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nquery GetCurrentMonthlyPeriod($userId: ID!) {\n  current_monthly_period(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nquery GetMonthlyPeriod($userId: ID!, $month: String!) {\n  monthly_period(userId: $userId, month: $month) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}": typeof types.GetMonthlyPeriodsDocument,
    "query SplitwiseAuthorizeUrl($userId: ID!) {\n  splitwise_authorize_url(userId: $userId) {\n    url\n  }\n}\n\nquery SplitwiseCredential($userId: ID!) {\n  splitwise_credential(userId: $userId) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nquery SplitwiseGroups($userId: ID!) {\n  splitwise_groups(userId: $userId) {\n    id\n    name\n    updated_at\n    members {\n      id\n      first_name\n      last_name\n      email\n    }\n  }\n}\n\nquery SplitwiseSettings($userId: ID!) {\n  splitwise_settings(userId: $userId) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}": typeof types.SplitwiseAuthorizeUrlDocument,
    "query SyncSourcesByAccount($userId: ID!, $account_id: Int!) {\n  sync_sources_by_account(userId: $userId, account_id: $account_id) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nquery AvailableBankTypes {\n  available_bank_types {\n    bank\n    types\n  }\n}": typeof types.SyncSourcesByAccountDocument,
    "query Transactions($userId: ID!, $limit: Int, $offset: Int) {\n  transactions(userId: $userId, limit: $limit, offset: $offset) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery TransactionsByAccount($userId: ID!, $account_id: Int!, $limit: Int, $offset: Int) {\n  transactions_by_account(\n    userId: $userId\n    account_id: $account_id\n    limit: $limit\n    offset: $offset\n  ) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery Transaction($userId: ID!, $id: Int!) {\n  transaction(userId: $userId, id: $id) {\n    id\n    transaction_id\n    account_id\n    amount\n    iso_currency_code\n    date\n    authorized_date\n    name\n    merchant_name\n    pending\n    payment_channel\n    created_at\n    updated_at\n  }\n}": typeof types.TransactionsDocument,
};
const documents: Documents = {
    "mutation DeactivateAccount($userId: ID!, $account_id: Int!) {\n  deactivate_account(userId: $userId, account_id: $account_id)\n}\n\nmutation AddAccount($userId: ID!, $input: AddAccountInput!) {\n  add_account(userId: $userId, input: $input) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}": types.DeactivateAccountDocument,
    "mutation UpdateBudgetBucket($userId: ID!, $bucketId: String!, $input: UpdateBudgetBucketInput!) {\n  update_budget_bucket(userId: $userId, bucket_id: $bucketId, input: $input) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}": types.UpdateBudgetBucketDocument,
    "mutation CreateMonthlyPeriod($userId: ID!, $input: CreateMonthlyPeriodInput!) {\n  create_monthly_period(userId: $userId, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nmutation UpdateMonthlyPeriod($userId: ID!, $id: Int!, $input: UpdateMonthlyPeriodInput!) {\n  update_monthly_period(userId: $userId, id: $id, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation CloseMonthlyPeriod($userId: ID!, $id: Int!) {\n  close_monthly_period(userId: $userId, id: $id) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation DeleteMonthlyPeriod($userId: ID!, $id: Int!) {\n  delete_monthly_period(userId: $userId, id: $id)\n}": types.CreateMonthlyPeriodDocument,
    "mutation SplitwiseCompleteOAuth($userId: ID!, $code: String!, $state: String!) {\n  splitwise_complete_oauth(userId: $userId, code: $code, state: $state) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nmutation SplitwiseDisconnect($userId: ID!) {\n  splitwise_disconnect(userId: $userId)\n}\n\nmutation SplitwiseUpdateSettings($userId: ID!, $input: UpdateSplitwiseSettingsInput!) {\n  splitwise_update_settings(userId: $userId, input: $input) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}": types.SplitwiseCompleteOAuthDocument,
    "mutation AddSyncSource($userId: ID!, $input: AddSyncSourceInput!) {\n  add_sync_source(userId: $userId, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation UpdateSyncSource($userId: ID!, $id: Int!, $input: UpdateSyncSourceInput!) {\n  update_sync_source(userId: $userId, id: $id, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation DeleteSyncSource($userId: ID!, $id: Int!) {\n  delete_sync_source(userId: $userId, id: $id)\n}\n\nmutation TestSyncSourceConnection($userId: ID!, $id: Int!) {\n  test_sync_source_connection(userId: $userId, id: $id) {\n    success\n    error_message\n  }\n}\n\nmutation SyncSyncSource($userId: ID!, $id: Int!) {\n  sync_sync_source(userId: $userId, id: $id) {\n    timestamp\n    emails_fetched\n    jobs_enqueued\n    errors\n    duration\n  }\n}": types.AddSyncSourceDocument,
    "query Accounts($userId: ID!) {\n  accounts(userId: $userId) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}": types.AccountsDocument,
    "query GetBudgetBuckets($userId: ID!) {\n  budget_buckets(userId: $userId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}\n\nquery GetBudgetBucket($userId: ID!, $bucketId: String!) {\n  budget_bucket(userId: $userId, bucket_id: $bucketId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}": types.GetBudgetBucketsDocument,
    "query GetMonthlyPeriods($userId: ID!) {\n  monthly_periods(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nquery GetCurrentMonthlyPeriod($userId: ID!) {\n  current_monthly_period(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nquery GetMonthlyPeriod($userId: ID!, $month: String!) {\n  monthly_period(userId: $userId, month: $month) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}": types.GetMonthlyPeriodsDocument,
    "query SplitwiseAuthorizeUrl($userId: ID!) {\n  splitwise_authorize_url(userId: $userId) {\n    url\n  }\n}\n\nquery SplitwiseCredential($userId: ID!) {\n  splitwise_credential(userId: $userId) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nquery SplitwiseGroups($userId: ID!) {\n  splitwise_groups(userId: $userId) {\n    id\n    name\n    updated_at\n    members {\n      id\n      first_name\n      last_name\n      email\n    }\n  }\n}\n\nquery SplitwiseSettings($userId: ID!) {\n  splitwise_settings(userId: $userId) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}": types.SplitwiseAuthorizeUrlDocument,
    "query SyncSourcesByAccount($userId: ID!, $account_id: Int!) {\n  sync_sources_by_account(userId: $userId, account_id: $account_id) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nquery AvailableBankTypes {\n  available_bank_types {\n    bank\n    types\n  }\n}": types.SyncSourcesByAccountDocument,
    "query Transactions($userId: ID!, $limit: Int, $offset: Int) {\n  transactions(userId: $userId, limit: $limit, offset: $offset) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery TransactionsByAccount($userId: ID!, $account_id: Int!, $limit: Int, $offset: Int) {\n  transactions_by_account(\n    userId: $userId\n    account_id: $account_id\n    limit: $limit\n    offset: $offset\n  ) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery Transaction($userId: ID!, $id: Int!) {\n  transaction(userId: $userId, id: $id) {\n    id\n    transaction_id\n    account_id\n    amount\n    iso_currency_code\n    date\n    authorized_date\n    name\n    merchant_name\n    pending\n    payment_channel\n    created_at\n    updated_at\n  }\n}": types.TransactionsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation DeactivateAccount($userId: ID!, $account_id: Int!) {\n  deactivate_account(userId: $userId, account_id: $account_id)\n}\n\nmutation AddAccount($userId: ID!, $input: AddAccountInput!) {\n  add_account(userId: $userId, input: $input) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["mutation DeactivateAccount($userId: ID!, $account_id: Int!) {\n  deactivate_account(userId: $userId, account_id: $account_id)\n}\n\nmutation AddAccount($userId: ID!, $input: AddAccountInput!) {\n  add_account(userId: $userId, input: $input) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation UpdateBudgetBucket($userId: ID!, $bucketId: String!, $input: UpdateBudgetBucketInput!) {\n  update_budget_bucket(userId: $userId, bucket_id: $bucketId, input: $input) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["mutation UpdateBudgetBucket($userId: ID!, $bucketId: String!, $input: UpdateBudgetBucketInput!) {\n  update_budget_bucket(userId: $userId, bucket_id: $bucketId, input: $input) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation CreateMonthlyPeriod($userId: ID!, $input: CreateMonthlyPeriodInput!) {\n  create_monthly_period(userId: $userId, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nmutation UpdateMonthlyPeriod($userId: ID!, $id: Int!, $input: UpdateMonthlyPeriodInput!) {\n  update_monthly_period(userId: $userId, id: $id, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation CloseMonthlyPeriod($userId: ID!, $id: Int!) {\n  close_monthly_period(userId: $userId, id: $id) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation DeleteMonthlyPeriod($userId: ID!, $id: Int!) {\n  delete_monthly_period(userId: $userId, id: $id)\n}"): (typeof documents)["mutation CreateMonthlyPeriod($userId: ID!, $input: CreateMonthlyPeriodInput!) {\n  create_monthly_period(userId: $userId, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nmutation UpdateMonthlyPeriod($userId: ID!, $id: Int!, $input: UpdateMonthlyPeriodInput!) {\n  update_monthly_period(userId: $userId, id: $id, input: $input) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation CloseMonthlyPeriod($userId: ID!, $id: Int!) {\n  close_monthly_period(userId: $userId, id: $id) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nmutation DeleteMonthlyPeriod($userId: ID!, $id: Int!) {\n  delete_monthly_period(userId: $userId, id: $id)\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation SplitwiseCompleteOAuth($userId: ID!, $code: String!, $state: String!) {\n  splitwise_complete_oauth(userId: $userId, code: $code, state: $state) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nmutation SplitwiseDisconnect($userId: ID!) {\n  splitwise_disconnect(userId: $userId)\n}\n\nmutation SplitwiseUpdateSettings($userId: ID!, $input: UpdateSplitwiseSettingsInput!) {\n  splitwise_update_settings(userId: $userId, input: $input) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["mutation SplitwiseCompleteOAuth($userId: ID!, $code: String!, $state: String!) {\n  splitwise_complete_oauth(userId: $userId, code: $code, state: $state) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nmutation SplitwiseDisconnect($userId: ID!) {\n  splitwise_disconnect(userId: $userId)\n}\n\nmutation SplitwiseUpdateSettings($userId: ID!, $input: UpdateSplitwiseSettingsInput!) {\n  splitwise_update_settings(userId: $userId, input: $input) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation AddSyncSource($userId: ID!, $input: AddSyncSourceInput!) {\n  add_sync_source(userId: $userId, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation UpdateSyncSource($userId: ID!, $id: Int!, $input: UpdateSyncSourceInput!) {\n  update_sync_source(userId: $userId, id: $id, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation DeleteSyncSource($userId: ID!, $id: Int!) {\n  delete_sync_source(userId: $userId, id: $id)\n}\n\nmutation TestSyncSourceConnection($userId: ID!, $id: Int!) {\n  test_sync_source_connection(userId: $userId, id: $id) {\n    success\n    error_message\n  }\n}\n\nmutation SyncSyncSource($userId: ID!, $id: Int!) {\n  sync_sync_source(userId: $userId, id: $id) {\n    timestamp\n    emails_fetched\n    jobs_enqueued\n    errors\n    duration\n  }\n}"): (typeof documents)["mutation AddSyncSource($userId: ID!, $input: AddSyncSourceInput!) {\n  add_sync_source(userId: $userId, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation UpdateSyncSource($userId: ID!, $id: Int!, $input: UpdateSyncSourceInput!) {\n  update_sync_source(userId: $userId, id: $id, input: $input) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nmutation DeleteSyncSource($userId: ID!, $id: Int!) {\n  delete_sync_source(userId: $userId, id: $id)\n}\n\nmutation TestSyncSourceConnection($userId: ID!, $id: Int!) {\n  test_sync_source_connection(userId: $userId, id: $id) {\n    success\n    error_message\n  }\n}\n\nmutation SyncSyncSource($userId: ID!, $id: Int!) {\n  sync_sync_source(userId: $userId, id: $id) {\n    timestamp\n    emails_fetched\n    jobs_enqueued\n    errors\n    duration\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query Accounts($userId: ID!) {\n  accounts(userId: $userId) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["query Accounts($userId: ID!) {\n  accounts(userId: $userId) {\n    id\n    name\n    bank\n    type\n    mask\n    current_balance\n    available_balance\n    iso_currency_code\n    is_active\n    created_at\n    updated_at\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetBudgetBuckets($userId: ID!) {\n  budget_buckets(userId: $userId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}\n\nquery GetBudgetBucket($userId: ID!, $bucketId: String!) {\n  budget_bucket(userId: $userId, bucket_id: $bucketId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["query GetBudgetBuckets($userId: ID!) {\n  budget_buckets(userId: $userId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}\n\nquery GetBudgetBucket($userId: ID!, $bucketId: String!) {\n  budget_bucket(userId: $userId, bucket_id: $bucketId) {\n    id\n    bucket_id\n    name\n    monthly_limit\n    color\n    is_active\n    created_at\n    updated_at\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetMonthlyPeriods($userId: ID!) {\n  monthly_periods(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nquery GetCurrentMonthlyPeriod($userId: ID!) {\n  current_monthly_period(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nquery GetMonthlyPeriod($userId: ID!, $month: String!) {\n  monthly_period(userId: $userId, month: $month) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}"): (typeof documents)["query GetMonthlyPeriods($userId: ID!) {\n  monthly_periods(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}\n\nquery GetCurrentMonthlyPeriod($userId: ID!) {\n  current_monthly_period(userId: $userId) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n  }\n}\n\nquery GetMonthlyPeriod($userId: ID!, $month: String!) {\n  monthly_period(userId: $userId, month: $month) {\n    id\n    user_id\n    month\n    projected_income\n    actual_income\n    status\n    notes\n    created_at\n    updated_at\n    is_open\n    is_closed\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query SplitwiseAuthorizeUrl($userId: ID!) {\n  splitwise_authorize_url(userId: $userId) {\n    url\n  }\n}\n\nquery SplitwiseCredential($userId: ID!) {\n  splitwise_credential(userId: $userId) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nquery SplitwiseGroups($userId: ID!) {\n  splitwise_groups(userId: $userId) {\n    id\n    name\n    updated_at\n    members {\n      id\n      first_name\n      last_name\n      email\n    }\n  }\n}\n\nquery SplitwiseSettings($userId: ID!) {\n  splitwise_settings(userId: $userId) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["query SplitwiseAuthorizeUrl($userId: ID!) {\n  splitwise_authorize_url(userId: $userId) {\n    url\n  }\n}\n\nquery SplitwiseCredential($userId: ID!) {\n  splitwise_credential(userId: $userId) {\n    id\n    user_id\n    splitwise_user_id\n    created_at\n    updated_at\n  }\n}\n\nquery SplitwiseGroups($userId: ID!) {\n  splitwise_groups(userId: $userId) {\n    id\n    name\n    updated_at\n    members {\n      id\n      first_name\n      last_name\n      email\n    }\n  }\n}\n\nquery SplitwiseSettings($userId: ID!) {\n  splitwise_settings(userId: $userId) {\n    id\n    user_id\n    included_group_ids\n    auto_sync_enabled\n    created_at\n    updated_at\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query SyncSourcesByAccount($userId: ID!, $account_id: Int!) {\n  sync_sources_by_account(userId: $userId, account_id: $account_id) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nquery AvailableBankTypes {\n  available_bank_types {\n    bank\n    types\n  }\n}"): (typeof documents)["query SyncSourcesByAccount($userId: ID!, $account_id: Int!) {\n  sync_sources_by_account(userId: $userId, account_id: $account_id) {\n    id\n    account_id\n    name\n    email_address\n    imap_host\n    imap_port\n    imap_folder\n    status\n    last_synced_at\n    last_processed_uid\n    is_active\n    created_at\n    balance_count\n    transaction_count\n  }\n}\n\nquery AvailableBankTypes {\n  available_bank_types {\n    bank\n    types\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query Transactions($userId: ID!, $limit: Int, $offset: Int) {\n  transactions(userId: $userId, limit: $limit, offset: $offset) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery TransactionsByAccount($userId: ID!, $account_id: Int!, $limit: Int, $offset: Int) {\n  transactions_by_account(\n    userId: $userId\n    account_id: $account_id\n    limit: $limit\n    offset: $offset\n  ) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery Transaction($userId: ID!, $id: Int!) {\n  transaction(userId: $userId, id: $id) {\n    id\n    transaction_id\n    account_id\n    amount\n    iso_currency_code\n    date\n    authorized_date\n    name\n    merchant_name\n    pending\n    payment_channel\n    created_at\n    updated_at\n  }\n}"): (typeof documents)["query Transactions($userId: ID!, $limit: Int, $offset: Int) {\n  transactions(userId: $userId, limit: $limit, offset: $offset) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery TransactionsByAccount($userId: ID!, $account_id: Int!, $limit: Int, $offset: Int) {\n  transactions_by_account(\n    userId: $userId\n    account_id: $account_id\n    limit: $limit\n    offset: $offset\n  ) {\n    transactions {\n      id\n      transaction_id\n      account_id\n      amount\n      iso_currency_code\n      date\n      authorized_date\n      name\n      merchant_name\n      pending\n      payment_channel\n      created_at\n    }\n    total\n  }\n}\n\nquery Transaction($userId: ID!, $id: Int!) {\n  transaction(userId: $userId, id: $id) {\n    id\n    transaction_id\n    account_id\n    amount\n    iso_currency_code\n    date\n    authorized_date\n    name\n    merchant_name\n    pending\n    payment_channel\n    created_at\n    updated_at\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;