/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as SetupRouteImport } from './routes/setup.tsx'
import { Route as RegisterRouteImport } from './routes/register.tsx'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as ProtectedRouteImport } from './routes/_protected.tsx'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedMonthlyRouteImport } from './routes/_protected/monthly.tsx'
import { Route as ProtectedAccountsRouteImport } from './routes/_protected/accounts.tsx'
import { Route as ProtectedBucketBucketIdRouteImport } from './routes/_protected/bucket/$bucketId.tsx'
import { Route as ProtectedAccountAccountIdRouteImport } from './routes/_protected/account/$accountId.tsx'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedMonthlyRoute = ProtectedMonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountsRoute = ProtectedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBucketBucketIdRoute = ProtectedBucketBucketIdRouteImport.update({
  id: '/bucket/$bucketId',
  path: '/bucket/$bucketId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAccountAccountIdRoute =
  ProtectedAccountAccountIdRouteImport.update({
    id: '/account/$accountId',
    path: '/account/$accountId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/accounts': typeof ProtectedAccountsRoute
  '/monthly': typeof ProtectedMonthlyRoute
  '/': typeof ProtectedIndexRoute
  '/account/$accountId': typeof ProtectedAccountAccountIdRoute
  '/bucket/$bucketId': typeof ProtectedBucketBucketIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/accounts': typeof ProtectedAccountsRoute
  '/monthly': typeof ProtectedMonthlyRoute
  '/': typeof ProtectedIndexRoute
  '/account/$accountId': typeof ProtectedAccountAccountIdRoute
  '/bucket/$bucketId': typeof ProtectedBucketBucketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_protected/accounts': typeof ProtectedAccountsRoute
  '/_protected/monthly': typeof ProtectedMonthlyRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/account/$accountId': typeof ProtectedAccountAccountIdRoute
  '/_protected/bucket/$bucketId': typeof ProtectedBucketBucketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/setup'
    | '/accounts'
    | '/monthly'
    | '/'
    | '/account/$accountId'
    | '/bucket/$bucketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/setup'
    | '/accounts'
    | '/monthly'
    | '/'
    | '/account/$accountId'
    | '/bucket/$bucketId'
  id:
    | '__root__'
    | '/_protected'
    | '/login'
    | '/register'
    | '/setup'
    | '/_protected/accounts'
    | '/_protected/monthly'
    | '/_protected/'
    | '/_protected/account/$accountId'
    | '/_protected/bucket/$bucketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/monthly': {
      id: '/_protected/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof ProtectedMonthlyRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/accounts': {
      id: '/_protected/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof ProtectedAccountsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/bucket/$bucketId': {
      id: '/_protected/bucket/$bucketId'
      path: '/bucket/$bucketId'
      fullPath: '/bucket/$bucketId'
      preLoaderRoute: typeof ProtectedBucketBucketIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/account/$accountId': {
      id: '/_protected/account/$accountId'
      path: '/account/$accountId'
      fullPath: '/account/$accountId'
      preLoaderRoute: typeof ProtectedAccountAccountIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedAccountsRoute: typeof ProtectedAccountsRoute
  ProtectedMonthlyRoute: typeof ProtectedMonthlyRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedAccountAccountIdRoute: typeof ProtectedAccountAccountIdRoute
  ProtectedBucketBucketIdRoute: typeof ProtectedBucketBucketIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAccountsRoute: ProtectedAccountsRoute,
  ProtectedMonthlyRoute: ProtectedMonthlyRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedAccountAccountIdRoute: ProtectedAccountAccountIdRoute,
  ProtectedBucketBucketIdRoute: ProtectedBucketBucketIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
